package com.ct.mybatis.model;

public class SAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_auth.RID
     *
     * @mbg.generated Thu Jun 07 13:32:17 CST 2018
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_auth.FID
     *
     * @mbg.generated Thu Jun 07 13:32:17 CST 2018
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_auth.RID
     *
     * @return the value of s_auth.RID
     *
     * @mbg.generated Thu Jun 07 13:32:17 CST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_auth.RID
     *
     * @param rid the value for s_auth.RID
     *
     * @mbg.generated Thu Jun 07 13:32:17 CST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_auth.FID
     *
     * @return the value of s_auth.FID
     *
     * @mbg.generated Thu Jun 07 13:32:17 CST 2018
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_auth.FID
     *
     * @param fid the value for s_auth.FID
     *
     * @mbg.generated Thu Jun 07 13:32:17 CST 2018
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}