package com.ct.mybatis.dao;

import com.ct.mybatis.model.SAuth;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_auth
     *
     * @mbg.generated Thu Jun 07 13:32:17 CST 2018
     */
    int deleteByPrimaryKey(@Param("rid") Integer rid, @Param("fid") Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_auth
     *
     * @mbg.generated Thu Jun 07 13:32:17 CST 2018
     */
    int insert(SAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_auth
     *
     * @mbg.generated Thu Jun 07 13:32:17 CST 2018
     */
    List<SAuth> selectAll();
}